name: "Continuous Integration"

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *' # Run every day, at 2AM UTC.

env:
  GOPATH: ${{ github.workspace }}
  WORKING_DIR: ./src/github.com/wcharczuk/sqslite

jobs:
  tests:
    name: "Tests"

    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}

    runs-on: ubuntu-latest

    env:
      GOOS: "linux"
      GOARCH: "amd64"
      GO111MODULE: "on"
      CGO_ENABLED: "0"

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Run all tests
      run: |
        go version
        ./scripts/test.sh

    - name: Code coverage
      uses: codecov/codecov-action@ad3126e916f78f00edff4ed0317cf185271ccc2d # v5.4.2
      with:
        file: ${{ env.WORKING_DIR }}/coverage.txt

  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Lint repository
        uses: golangci/golangci-lint-action@v8