name: "Continuous Integration"

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *' # Run every day, at 2AM UTC.

env:
  GOOS: "linux"
  GOARCH: "amd64"
  GO111MODULE: "on"
  CGO_ENABLED: "1"

jobs:
  tests:
    name: "Tests"

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Run all tests
      run: |
        go version
        go test -race ./...

  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Lint repository
        uses: golangci/golangci-lint-action@v8